### PR TITLE
updated pandas workshop

### LINKED ISSUE #1: Update pandas workshop
Hi @taniaturdean here are some TODOs for you in this workshop

- [x] Familiarise yourself with the material
- [x] Update, modify and improve which ever parts you like
- [x] gitignore things like .DS_Store, notebook checkpoints and IDE settings
- [x] Write a good README
- [x] Improve the directory structure: move the datasets to a separated folder like `data/` or `assets/` and change in the codes wherever these paths are used.

### PR DESCRIPTION
**Pull request by taniaturdean**

### CODE REVIEW

**Comment by TonyWu3027** [comment]
Hi @taniaturdean great work thanks! Just a bit more things and it's good for a merge:

- [ ] Please move all the datasets to a directory called `assets/` or `data/`
- [ ] Please change in the workshop material, problem and solution notebooks where those datasets are used so that are referred to with the right relative path. For instance: change the path `"H20.csv"` to `"assets/H20.csv"` or `"data/H20.csv"`

**Comment by taniaturdean** [comment]
@TonyWu3027 thanks!

I downloaded the workshop in my computer and it doesn't find the csv file if I write it "assets/H20.csv" and move the csv to assets. I found some articles saying you need to mention the path like 'c:/Windows', '/Program Files' for example, but I think this won't work for a lot of people doing the workshop as they will need to change the path to their folder and will be different for everyone

**Comment by TonyWu3027** [comment]
@taniaturdean Okay I see, I think `"./assets/H2O.csv"` should work since that's the relative path. Can you give it a shot? If it doesn't work then no worries I will just merge this version. Anyways great job!

**Comment by taniaturdean** [comment]
@TonyWu3027 I just tried that now, and still the same error: file does not exist

**Comment by TonyWu3027** [comment]
@taniaturdean Alright no worries, I'm merging this PR, thanks! btw please go to the Teams channel and create your meeting schedule there, I've created the one for Eric's this week, you can use that template, thanks and great work here!

**Pull request merged**
